In [2]:
import numpy as np, pandas as pd

In [3]:
# 创建一个测试DataFrame
frame = pd.DataFrame(np.random.randn(10,10),columns=['a','b','c','d','e','f','g','h','j','k'])
frame

,a,b,c,d,e,f,g,h,j,k
0,0.746792,-0.195354,-0.140151,-1.818676,-0.319827,-1.247586,-0.738229,0.181900,-0.682248,-1.060047
1,1.116677,0.285902,-0.930873,-1.108862,-0.033841,0.509090,0.128076,0.316550,0.167424,-0.317823
2,0.757637,-0.021594,1.071627,-0.385852,1.019750,-0.225667,0.724641,0.548997,1.041946,-0.250818
3,0.951427,-1.249828,1.285333,-0.104667,-1.559923,-1.506064,-2.690874,1.557701,-0.170092,0.133789
4,0.596119,0.157134,2.039012,-0.107457,0.768636,0.248853,-0.294697,0.548660,-1.775603,1.448469
5,0.763031,0.077158,0.549985,-0.455371,1.913476,1.792834,0.245323,1.553141,0.832104,-0.659579
6,-0.637839,0.135045,0.371720,-0.249616,-0.331437,0.185075,1.448585,-1.012811,0.045327,-1.655174
7,-0.621564,1.913761,-1.188280,0.068192,2.433113,1.143900,-1.751406,0.939807,-0.610016,0.105377
8,1.483085,0.832020,1.167165,-0.604320,1.718753,-1.109097,1.150078,0.814201,-0.660958,-1.431733
9,-0.251502,0.467598,-1.479515,-0.964273,-1.113252,-0.439828,-0.718123,0.165622,0.212204,-1.341362

In [4]:
# 单列求和
frame['c'].sum()

2.746022918540918

In [5]:
# 单行求和
frame.sum(axis = 'columns')

0   -5.273426
1    0.132320
2    4.280668
3   -3.353198
4    3.629126
5    6.612104
6   -1.701127
7    2.432884
8    3.359194
9   -5.462432
dtype: float64

In [6]:
# NaN值处理，顾及NaN值
frame
frame.sum(axis=1,skipna=False)

0   -5.273426
1    0.132320
2    4.280668
3   -3.353198
4    3.629126
5    6.612104
6   -1.701127
7    2.432884
8    3.359194
9   -5.462432
dtype: float64

In [7]:
frame

,a,b,c,d,e,f,g,h,j,k
0,0.746792,-0.195354,-0.140151,-1.818676,-0.319827,-1.247586,-0.738229,0.181900,-0.682248,-1.060047
1,1.116677,0.285902,-0.930873,-1.108862,-0.033841,0.509090,0.128076,0.316550,0.167424,-0.317823
2,0.757637,-0.021594,1.071627,-0.385852,1.019750,-0.225667,0.724641,0.548997,1.041946,-0.250818
3,0.951427,-1.249828,1.285333,-0.104667,-1.559923,-1.506064,-2.690874,1.557701,-0.170092,0.133789
4,0.596119,0.157134,2.039012,-0.107457,0.768636,0.248853,-0.294697,0.548660,-1.775603,1.448469
5,0.763031,0.077158,0.549985,-0.455371,1.913476,1.792834,0.245323,1.553141,0.832104,-0.659579
6,-0.637839,0.135045,0.371720,-0.249616,-0.331437,0.185075,1.448585,-1.012811,0.045327,-1.655174
7,-0.621564,1.913761,-1.188280,0.068192,2.433113,1.143900,-1.751406,0.939807,-0.610016,0.105377
8,1.483085,0.832020,1.167165,-0.604320,1.718753,-1.109097,1.150078,0.814201,-0.660958,-1.431733
9,-0.251502,0.467598,-1.479515,-0.964273,-1.113252,-0.439828,-0.718123,0.165622,0.212204,-1.341362

In [8]:
# 返回每一列最大值的index
frame.idxmax()

a    8
b    7
c    4
d    7
e    7
f    5
g    6
h    3
j    2
k    4
dtype: int64

In [12]:
# 第n个元素返回所在列前n个元素的累加值
frame.cumsum()

,a,b,c,d,e,f,g,h,j,k
0,0.746792,-0.195354,-0.140151,-1.818676,-0.319827,-1.247586,-0.738229,0.181900,-0.682248,-1.060047
1,1.863468,0.090548,-1.071023,-2.927538,-0.353668,-0.738495,-0.610154,0.498450,-0.514824,-1.377870
2,2.621106,0.068954,0.000604,-3.313390,0.666082,-0.964162,0.114487,1.047447,0.527122,-1.628688
3,3.572532,-1.180874,1.285936,-3.418057,-0.893841,-2.470225,-2.576387,2.605148,0.357030,-1.494900
4,4.168652,-1.023740,3.324948,-3.525514,-0.125205,-2.221373,-2.871083,3.153809,-1.418573,-0.046431
5,4.931683,-0.946582,3.874933,-3.980884,1.788271,-0.428539,-2.625760,4.706950,-0.586469,-0.706009
6,4.293844,-0.811537,4.246653,-4.230501,1.456834,-0.243464,-1.177175,3.694139,-0.541142,-2.361184
7,3.672279,1.102224,3.058373,-4.162308,3.889947,0.900436,-2.928581,4.633946,-1.151158,-2.255807
8,5.155364,1.934244,4.225538,-4.766628,5.608700,-0.208661,-1.778503,5.448147,-1.812116,-3.687539
9,4.903862,2.401842,2.746023,-5.730901,4.495448,-0.648489,-2.496626,5.613768,-1.599913,-5.028902

In [21]:
# 非归约也非累计，产生汇总统计结果
descFrame = frame.describe()
print(descFrame)

               a          b          c          d          e          f  \
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000
mean    0.490386   0.240184   0.274602  -0.573090   0.449545  -0.064849
std     0.735803   0.797762   1.178231   0.576731   1.334637   1.061196
min    -0.637839  -1.249828  -1.479515  -1.818676  -1.559923  -1.506064
25%    -0.039597   0.003094  -0.733192  -0.874285  -0.328535  -0.941780
50%     0.752215   0.146089   0.460853  -0.420611   0.367397  -0.020296
75%     0.904328   0.422174   1.143281  -0.142997   1.544002   0.444031
max     1.483085   1.913761   2.039012   0.068192   2.433113   1.792834

               g          h          j          k
count  10.000000  10.000000  10.000000  10.000000
mean   -0.249663   0.561377  -0.159991  -0.502890
std     1.284748   0.747019   0.820118   0.937459
min    -2.690874  -1.012811  -1.775603  -1.655174
25%    -0.733203   0.215563  -0.648223  -1.271034
50%    -0.083310   0.548829  -0.062383  -0.488701
75%     0.604811   0.908406   0.201009   0.016328
max     1.448585   1.557701   1.041946   1.448469

In [25]:
# 非NaN的值的个数
frame.count()

a    10
b    10
c    10
d    10
e    10
f    10
g    10
h    10
j    10
k    10
dtype: int64

In [27]:
# 索引位置和标签
print(descFrame.idxmax())# 返回index标签
descFrame['b'].argmax()# 返回索引整数

a    count
b    count
c    count
d    count
e    count
f    count
g    count
h    count
j    count
k    count
dtype: object

0